> np 모듈 호출  

In [2]:
import numpy as np

> 정상적으로 호출이 됐는지 확인

In [4]:
a=np.array(1)
a

array(1)

> 배열생성 object>string>float>int

In [6]:
ndarr_1= np.array([1,2,3])
print(ndarr_1)

[1 2 3]


In [7]:
ndarr_2 = np.array([1,2.0,3])
print(ndarr_2)

[1. 2. 3.]


In [8]:
ndarr_3 = np.array([1,2.0,'3'])
print(ndarr_3)

['1' '2.0' '3']


> 배열의 정보 확인 ndarray.dtype

In [9]:
print(ndarr_1.dtype)
print(ndarr_2.dtype)
print(ndarr_3.dtype)

int32
float64
<U32


In [10]:
print(np.array(1+2j).dtype)
print(np.array(print).dtype)

complex128
object


dtype 속성을 사용하여 자료형 지정

In [12]:
dtype1 = np.array([1,2,3],dtype=np.int8)
print(dtype1.dtype)

int8


In [14]:
dtype2 = np.array([1,2,3],dtype=float)
print(dtype2.dtype)

float64


In [16]:
dtype3 = np.array([1,2,3],dtype=str)
print(dtype3.dtype)

<U1


### 주의해야 할 점 

In [17]:
dtype4 = np.array([1,2,'3'],dtype=int)
print(dtype4)
print(dtype4.dtype)

[1 2 3]
int32


In [18]:
dtype5 = np.array([1,'data',print],dtype=float) # 오류 
print(dtype5)
print(dtype5.dtype)

ValueError: could not convert string to float: 'data'

> 배열 크기 확인

In [19]:
print(ndarr_1.shape)

(3,)


> 배열 차원 확인 

In [20]:
print(ndarr_1.ndim)

1
