> 1차원 배열생성

In [2]:
import numpy as np
vector = np.array([1,2,3])
print(vector)
print(vector.shape)
print(vector.ndim)
print(vector.dtype)

[1 2 3]
(3,)
1
int32


> 2차원 배열 생성

In [5]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)
print(matrix.shape)
print(matrix.ndim)
print(matrix.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int32


> 3차원 배열 생성 

In [6]:
tensor = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor)
print(tensor.shape)
print(tensor.ndim)
print(tensor.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
3
int32


> 배열의 정보 확인

In [8]:
print(vector.size)
print(matrix.size)
print(tensor.size)

3
6
12


- 배열생성

In [17]:
matrix2 = np.array([[1,2,3],[2,4,6],[3,6,9]])
print(matrix2)
print(matrix2.ndim)
print(matrix2.size)
print(matrix2.shape)
print(matrix2.dtype)

[[1 2 3]
 [2 4 6]
 [3 6 9]]
2
9
(3, 3)
int32


## 자료형 변환(리스트)

> 리스트 -> ndarray 변환

In [18]:
list1 =[1,2,3]
arr1 =np.array(list1)
print(arr1)

[1 2 3]


> ndarray -> 리스트 변환

In [19]:
arr2 = np.array([1,2,3])
list2 = list(arr2)
print(list2)

[1, 2, 3]


> 2차원 리스트 변환

In [20]:
list3 = [[1,2,3],[4,5,6]]
arr3=np.array(list3)
print(arr3)

[[1 2 3]
 [4 5 6]]


> shape이 다른 리스트인 경우 

In [22]:
list4 = [[1,2,3,4],[5,6,7]] # 데이터 길이 달라서 경고 
arr4 = np.array(list4)
print(arr4)
print(arr4.size, arr4.shape, arr4.ndim)

[list([1, 2, 3, 4]) list([5, 6, 7])]
2 (2,) 1


C:\Users\82102\AppData\Local\Temp\ipykernel_8856\3322727475.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr4 = np.array(list4)


> 튜블 -> ndarray 변환

In [24]:
tuple1 = (1,2,3)
arr = np.array(tuple1)
print(arr)

[1 2 3]


> ndarrary -> 튜플 변환

In [25]:
arr2 = np.array([1,2,3])
tuple2 = tuple(arr2)
print(tuple2)

(1, 2, 3)


## 자료형 변환(세트, 딕셔너리)

> 세트변환 # 세트는 np.array 변환 불가능 

In [29]:
set1 = {1,2,3}
arr=np.array(set1)
print(arr,arr.size,arr.shape) # shape는 스칼라에서 () 


{1, 2, 3} 1 ()


> 딕셔너리 변환

In [31]:
dict1 = {'a':1, 'b':2, 'c':3}
arr= np.array(dict1)
print(arr, arr.size)

{'a': 1, 'b': 2, 'c': 3} 1


## 배열 인덱싱

> 리스트 인덱싱과 유사 

In [35]:
list_ = [[[1,2],[3,4]],[[5,6],[7,8]]]
print(list_)
# 1 가져오기
print(list_[0][0][0])
# 4 가져오기
print(list_[0][1][1])
# 7 가져오기
print(list_[1][1][0])


[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
1
4
7


In [40]:
arr_ = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr_)
# 1 가져오기
print(arr_[0][0][0])
# 4 가져오기
print(arr_[0][1][1])
# 7 가져오기
print(arr_[1][1][0])


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
1
4
7


> ndarray의 인덱싱

In [42]:
arr_ = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr_[0,0,0])
print(arr_[0,1,1])
print(arr_[1,1,0])

1
4
7


In [45]:
arr_1 = np.array([[1,2],[3,4],[5,6]])
# 0행 가져와 2차원 배열 만들기
print(arr_1[[0]]) # row 다중선택
print('\n')
#0,2행 가져와 2차원 배열 만들기
print(arr_1[[0,2]])
print('\n')
# 다음 결과는?
print(arr_1[[0,1,2],[0,1,0]])
print('\n')
# 같은 위치 데이터 여러번 사용가능
print(arr_1[[0,0],[1,1]]) # 

[[1 2]]


[[1 2]
 [5 6]]


[1 4 5]


[2 2]


In [70]:
arr2_=np.array([[1,2,3,],[4,5,6,],[7,8,9],[10,11,12]])
# 두개의 1차원 배열 만들기
b = np.array([0,1,2,3])
c = np.array([0,2,0,1])     
print(arr2_[b,c])


[ 1  6  7 11]


In [76]:
arr = np.array([1,2,3,4,5])
print(arr[arr>= 3])


[3 4 5]


In [79]:
# True, False
print(arr[[True, False,True, False,True]])


[1 3 5]


- [문제2]

In [69]:
score = np.array([[78,91,84,89,93,65],[82,87,96,79,91,73]])
print(score[0][score[0]>=90])
print(score[1][score[1]>=90])

[91 93]
[96 91]
