# NUMPY 활용 

###  Reshape

> array.reshpae(size)

In [2]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]]) #2x3형태의 2차원 배열
print(arr.reshape(3,2)) # 3x2형태의 2차원 배열 

[[1 2]
 [3 4]
 [5 6]]


In [4]:
print(arr.reshape(6,1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [6]:
print(arr.reshape(1,6))

[[1 2 3 4 5 6]]


> 3x1x2 배열로 변형 

In [12]:
print(arr.reshape(3,1,2))

[[[1 2]]

 [[3 4]]

 [[5 6]]]


In [9]:
print(arr.reshape(3,1,2,1)) # 차원 늘리고 싶으면 , 늘려서 
print(arr.reshape(6)) # 차원 줄이고 싶으면 , 줄이기 

[1 2 3 4 5 6]


> ?x2 배열로 변형 

In [8]:
print(arr.reshape(-1,2))

[[1 2]
 [3 4]
 [5 6]]


In [13]:
tensor = np.array(range(1,37)) # shape (3,3,4)

In [14]:
print(tensor.reshape(3,3,4))

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]


- tensor 배열을 2차원 배열로 변형시켜 봅니다. * 열의 개수는 9

In [15]:
print(tensor.reshape(-1,9))

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36]]


# Flatten

> 다차원 배열을 1차원배열로 변형 

In [18]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
# shape(2,3) -> shape(6,)
print(arr.flatten())

[1 2 3 4 5 6]


In [17]:
# shape(1,6) -> shape(6,)
print(arr.reshape(1,6).flatten())

[1 2 3 4 5 6]


In [24]:
tensor2 = tensor.reshape(3,3,4)
tensor2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]]])

In [25]:
print(tensor2.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


# Arange 

In [26]:
print(np.arange(30)) # np.array(range(30))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


> 간격지정 : np.arange(start,end,step)

In [27]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [28]:
print(np.arange(0,2,0.2))

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]


In [29]:
print(np.arange(-2,2,0.5))

[-2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5]


In [30]:
print(np.arange(10,0,-1))

[10  9  8  7  6  5  4  3  2  1]


# Arange + Reshape 

In [31]:
print(np.arange(1,26).reshape(5,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


- 문제3. arange, reshape 함수 사용 100부터 190까지 숫자가 10 간격으로 나열된 배열 생성, (2,5) 형태의 2차원 배열로 변형 

In [33]:
arr_test_3 = np.arange(100,191,10).reshape(2,5)
print(arr_test_3)

[[100 110 120 130 140]
 [150 160 170 180 190]]


- 문제 4 arange, reshape 함수 사용 -2부터 2까지의 숫자가 0.5 간격으로 나열된 배열생성,적당한 3차원배열로 변경

In [40]:
arr_test_4 = np.arange(-2,2.1,0.5).reshape(3,3,1)
print(arr_test_4)

[[[-2. ]
  [-1.5]
  [-1. ]]

 [[-0.5]
  [ 0. ]
  [ 0.5]]

 [[ 1. ]
  [ 1.5]
  [ 2. ]]]


# Zeros

> np.zeros(shape, dtype) 

 0으로 채워진 배열 생성 , shape 지정 가능 

In [48]:
print(np.zeros(shape=(5,),dtype=np.int8))

[0 0 0 0 0]


In [53]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


# Ones

> np.ones(shape,dtype)

In [47]:
print(np.ones(shape=(5,),dtype=np.int8))

[1 1 1 1 1]


# Empty

> np.empty(shape,dtype)

In [51]:
print(np.empty(shape =(10,),dtype=np.int32))

[100 110 120 130 140 150 160 170 180 190]


In [52]:
print(np.empty((2,5),np.int8))

[[0 1 1 1 1]
 [1 1 1 1 1]]


# Zeros_like / Ones_like / Empty_like

> np.zeros_like(ndarray)

In [55]:
matrix = np.arange(24).reshape(4,6)
print(np.zeros_like(matrix))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


>np.ones_like(ndarray)

In [56]:
matrix = np.arange(-2,2,0.2).reshape(2,10)
print(np.ones_like(matrix))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


>np.empty_like(ndarray)

In [58]:
matrix = np.arange(30).reshape(5,6)
print(np.empty_like(matrix))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [64]:
print(np.empty_like(matrix))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


# Identity : 단위행렬

>np.identity(size,dtype)

In [65]:
print(np.identity(5, dtype =np.int8))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [66]:
print(np.identity(2))

[[1. 0.]
 [0. 1.]]


In [67]:
print(np.identity(5, dtype=np.str_))

[['1' '' '' '' '']
 ['' '1' '' '' '']
 ['' '' '1' '' '']
 ['' '' '' '1' '']
 ['' '' '' '' '1']]


# Eye : 대각선이 1로 채워지는 행렬 , 대각선의 위치지정가능

> np.eye(size,M,k,dtype)


     -  k : 대각선의 시작 위치를 입력 받은 수 만큼 오른쪽으로 이동
     -  M : 보여지는 열의 개수를 지정 

In [68]:
print(np.eye(5,dtype=np.int8))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [72]:
print(np.eye(5, k = 2))

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [73]:
print(np.eye(5, M=10, k =-1))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]


In [74]:
print(np.eye(5, M = 10, k = 5))

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


# Full

입력 값으로 채워지는 행렬

> np.full((Shape),value)

In [77]:
print(np.full((2,5),3))

[[3 3 3 3 3]
 [3 3 3 3 3]]


In [78]:
print(np.full((2,5),'Python'))

[['Python' 'Python' 'Python' 'Python' 'Python']
 ['Python' 'Python' 'Python' 'Python' 'Python']]


In [84]:
print(np.ones((3,3))*3)
print(np.full((3,3),3))

[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]


# Random.randint

주어진 범위 안의 랜덤한 값을 뽑는 함수

> np.random.randint(range)

In [93]:
#0~5까지의 정수중 하나뽑기
print(np.random.randint(6))

3


In [117]:
print(np.random.randint(1,20,2)) # 1~19 까지 정수중 2개 뽑아서 배열 만들기 

[10 10]


In [94]:
import random

In [116]:
# 0~10까지의 정수중 하나뽑기 (다른함수 사용)
random.randint(0,10)

8

# Random.rand

랜덤한 값으로 채워지는 배열 

표준정규 분포 난수를 shape 형태의 배열로 생성 0~1 사의 값 가짐


> np.random.rand(shape)

In [118]:
print(np.random.rand(3))

[0.13047547 0.60452905 0.73813729]


In [119]:
print(np.random.rand(3,2)) # 3x2 행렬 

[[0.8617111  0.77267906]
 [0.48883998 0.18738665]
 [0.91903858 0.78923856]]


# Random.randn

랜덤한 값으로 채워지는 배열 , 음수도 출력

평균 0, 표준편차1의 가우시안 표준정규분포 난수를 shape 형태의 배열로 생성

> np.random.randn(shape)

In [120]:
print(np.random.randn(3))

[ 0.50049703 -1.01344268 -0.07941236]


In [121]:
print(np.random.randn(3,2))

[[ 0.50532035  0.73125224]
 [ 0.49777663 -0.96005935]
 [-0.22108018  1.17919241]]
