# 연산함수

## 합

> ndarray.sum()

In [6]:
import numpy as np
matrix = np.arange(1,7).reshape(2,3)
print(matrix.sum())

21


In [7]:
print(matrix.sum(axis=0))

[5 7 9]


In [8]:
print(matrix.sum(axis=1))

[ 6 15]


> 3차원배열 합 

In [9]:
tensor = np.arange(1,19).reshape(3,2,3)
print(tensor)
print(tensor.sum())

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
171


In [10]:
print(tensor.sum(axis=0))

[[21 24 27]
 [30 33 36]]


In [11]:
print(tensor.sum(axis=1))

[[ 5  7  9]
 [17 19 21]
 [29 31 33]]


In [12]:
print(tensor.sum(axis=2)) 

[[ 6 15]
 [24 33]
 [42 51]]


## 평균

In [16]:
print(matrix.mean())
print(matrix.mean(axis=0)) # 행끼리 평균(위아래)
print(matrix.mean(axis=1)) # 열끼리 평균 (좌우)

3.5
[2.5 3.5 4.5]
[2. 5.]


In [19]:
sum(tensor)# axis 사용불가능 

array([[21, 24, 27],
       [30, 33, 36]])

In [20]:
tensor.sum() # axis 사용가능 

171

In [22]:
np.sum(tensor)# axis 사용가능 

171

In [26]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
print(matrix.mean())

3.5


In [25]:
print(matrix.mean(axis=0))

[2.5 3.5 4.5]


## 표준편차

In [28]:
print(matrix.std()) # 전체표준편차
print(matrix.std(axis=0))# 행끼리 표준편차 (위아래)
print(matrix.std(axis=1))# 열끼리 표준편차 (좌우)

1.707825127659933
[1.5 1.5 1.5]
[0.81649658 0.81649658]


## 그 외 수학연산자

In [29]:
# 지수(exp)
print(np.exp(matrix))

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [30]:
# 로그(log)
print(np.log(matrix))

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]


In [31]:
# 제곱근
print(np.sqrt(matrix))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [32]:
# 삼각함수(sin)
print(np.sin(matrix))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


In [33]:
# 삼각함수(cos)
print(np.cos(matrix))

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]


In [34]:
# 삼각함수(tan)
print(np.tan(matrix))

[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]]
