# 배열정렬

## 1차원 배열 정렬

In [4]:
import numpy as np
# 1 ~ 100 까지 숫자 다섯개 뽑아서 리스트에 저장 
vector = np.array([np.random.randint(1,100)
                  for n in range(5)])
print(vector)

[50 56 76 95  5]


In [5]:
print(np.sort(vector)) # 오름차순 정렬 

[ 5 50 56 76 95]


In [8]:
print(np.sort(vector)[::-1]) # 내림차순 정렬 

[95 76 56 50  5]


- list내 for 문 

In [9]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [10]:
x = 3
[x for i in range(5) if x== i]

[3]

In [12]:
list_ =[1,2,3,4,5,6,7,8,9,10]
list2_ =[num*3 for num in list_ if num % 2 ==1] # list_ 값중에 2로 나눴을때 나머지가 1인 값들에 3을 곱해준값을 다시 리스트에 저장
list2_

[3, 9, 15, 21, 27]

> 2차원 배열

In [15]:
# randint를 사용하여 1~100 숫자중 20개를 뽑아 4x5 배열 생성
matrix = np.array([np.random.randint(1,100)
                   for n in range(20)]).reshape(4,5)
print(matrix)

[[21 88 84 38 81]
 [73 56  1 95  7]
 [ 8 15 63 99 78]
 [54 48 88 69 12]]


In [16]:
print(np.sort(matrix))# 열기준 정렬 (좌우)

[[21 38 81 84 88]
 [ 1  7 56 73 95]
 [ 8 15 63 78 99]
 [12 48 54 69 88]]


In [17]:
print(np.sort(matrix,axis=0)) # 행기준 정렬(위아래)

[[ 8 15  1 38  7]
 [21 48 63 69 12]
 [54 56 84 95 78]
 [73 88 88 99 81]]


## 배열 합치기


> np.vstack([arr1,arr2]) 수평

In [21]:
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])
print(np.vstack([vector1, vector2]))

[[1 2 3]
 [4 5 6]]


> np.hstack([arr1,arr2]) 수직

In [20]:
vector1 = np.array([1,2,3]).reshape(3,1)
vector2 = np.array([4,5,6]).reshape(3,1)
print(np.hstack([vector1, vector2]))

[[1 4]
 [2 5]
 [3 6]]


> np.concatenate(arr1,arr2,axis) 2개이상의 배열을 수직 수평으로 합체

In [35]:
vector1=np.array([[1,2,3]])
vector2=np.array([[4,5,6]])
print(np.concatenate([vector1,vector2],axis=1))

[[1 2 3 4 5 6]]


In [29]:
vector1=np.array([[1,2,3]])
vector2=np.array([[4,5,6]])
print(np.concatenate([vector1,vector2],axis=0)) # 세로로 합치기 

[[1 2 3]
 [4 5 6]]


In [32]:
vector1=np.array([1,2,3]).reshape(3,1)
vector2=np.array([4,5,6]).reshape(3,1)
print(np.concatenate([vector1,vector2],axis=1))# 가로로 

[[1 4]
 [2 5]
 [3 6]]


In [38]:
matrix1 = np.array([[1,2,3],[1,2,3]]).reshape(3,2)
vector2 = np.array([4,5,6]).reshape(3,1)

print(np.concatenate([matrix1, vector2], axis=1))

[[1 2 4]
 [3 1 5]
 [2 3 6]]


In [39]:
matrix1=np.arange(1,5).reshape(2,2)
matrix2=np.arange(5,9).reshape(2,2)
print(np.concatenate([matrix1,matrix2],axis=0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [40]:
matrix1=np.arange(1,5).reshape(2,2)
matrix2=np.arange(5,9).reshape(2,2)
print(np.concatenate([matrix1,matrix2],axis=1))

[[1 2 5 6]
 [3 4 7 8]]


## 행/열 바꾸기 (transpose)

> ndarray.transpose() 

> ndarray.T

In [43]:
matrix3 = np.array([[5,6]])
print(matrix3)

[[5 6]]


In [44]:
print(matrix3.transpose())

[[5]
 [6]]


In [45]:
print(matrix3.shape, matrix3.transpose().shape)

(1, 2) (2, 1)


In [46]:
print(matrix3.T)

[[5]
 [6]]


## Transpose+ Concatenate

In [48]:
print(np.concatenate([matrix1, matrix3]))

[[1 2]
 [3 4]
 [5 6]]


In [51]:
print(np.concatenate([matrix1, matrix3.T],axis=1)) # matrix의 행/열 바꾼뒤 Concatenate 실행 

[[1 2 5]
 [3 4 6]]


## 인덱스 반환함수 


> argmax, argmin # 최대값 최소값의 인덱스

In [53]:
a =np.arange(1,11).reshape(2,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [55]:
print(np.argmax(a),np.argmin(a)) # 값의 인덱스 값을 출력 

9 0


In [58]:
b=np.array([[1,2,3,4],[2,3,4,1],[3,4,1,2]])
print(b)

[[1 2 3 4]
 [2 3 4 1]
 [3 4 1 2]]


In [59]:
print(np.argmax(b,axis=1))

[3 2 1]


In [60]:
print(np.argmax(b,axis=0))

[2 2 1 0]


In [61]:
print(np.argmin(b,axis=0))

[0 0 2 1]


## 배열 인덱싱 (Fancy Index)

In [63]:
a = np.arange(1,11)
b = np.array([3,4,5,6])
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[3 4 5 6]


In [64]:
print(a[b])

[4 5 6 7]


In [ ]:
a = np.arange(10,20)
b = np.argmax(a)
print(a)
print(b) # 제일 높은 값을 가지는 인덱스 번호 출력 

In [67]:
print(a[b])

19
