# 배열연산


## 산술연산


In [2]:
import numpy as np
list1 = [1,2,3]
list2 = [4,5,6]
print(list1+list2)

[1, 2, 3, 4, 5, 6]


In [3]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1+arr2)

[5 7 9]


> 모양이 같은 배열 연산


In [4]:
arr1 = np.arange(1,7,dtype = np.float32).reshape(2,3)
arr2 = np.arange(11,17,dtype = np.int32).reshape(2,3)
print(arr1+arr2)

[[12. 14. 16.]
 [18. 20. 22.]]


In [5]:
print(arr2-arr1)

[[10. 10. 10.]
 [10. 10. 10.]]


In [6]:
print(arr1*arr2)

[[11. 24. 39.]
 [56. 75. 96.]]


In [7]:
print(arr1/arr2)

[[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]]


In [8]:
print(arr1**arr2)

[[1.00000000e+00 4.09600000e+03 1.59432300e+06]
 [2.68435456e+08 3.05175781e+10 2.82110991e+12]]


In [9]:
print(arr2//arr1)

[[11.  6.  4.]
 [ 3.  3.  2.]]


In [10]:
print(arr2%arr1)

[[0. 0. 1.]
 [2. 0. 4.]]


## Numpy의 연산함수


> np.add(arr1, arr2)


In [16]:
print(np.add(arr1,arr2))

[[12. 14. 16.]
 [18. 20. 22.]]


> np.subtract(arr1,arr2)

In [14]:
print(np.subtract(arr1,arr2))

[[-10. -10. -10.]
 [-10. -10. -10.]]


> np.multiply(arr1,arr2)

In [18]:
print(np.multiply(arr1,arr2))

[[11. 24. 39.]
 [56. 75. 96.]]


> np.divide(arr1,arr2)

In [19]:
print(np.divide(arr1,arr2))

[[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]]


> Broadcasting : 연산하고자 하는 배열의 모양이 다른 경우의 연산

> 배열과 스칼라의 연산 

In [20]:
scalar =10
vector = np.array([1,2,3])
print(scalar+vector)

[11 12 13]


In [21]:
scalar =10
matrix = np.array([[1,2,3],[4,5,6]])
print(scalar+matrix)

[[11 12 13]
 [14 15 16]]


In [22]:
scalar = 10
tensor = np.array([[[1,2,3],[4,5,6]],
                  [[7,8,9],[10,11,12]],
                  [[13,14,15],[16,17,18]]])
print(scalar + tensor)

[[[11 12 13]
  [14 15 16]]

 [[17 18 19]
  [20 21 22]]

 [[23 24 25]
  [26 27 28]]]


In [24]:
scalar = 10
matrix = np.array([[1,2,3],[4,5,6]])
print(scalar%matrix)

[[0 0 1]
 [2 0 4]]


> vector와 matrix의 연산 

In [23]:
matrix = np.arange(1,10).reshape(3,3)
vector = np.arange(11,14).reshape(1,3)
print(matrix+vector)

[[12 14 16]
 [15 17 19]
 [18 20 22]]


In [25]:
matrix = np.arange(1,10).reshape(3,3)
vector = np.arange(11,14).reshape(3,1)
print(matrix+vector)

[[12 13 14]
 [16 17 18]
 [20 21 22]]


> vector와 vector의 broadcasting 연산

In [26]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3]).reshape(3,1)
print(arr1)
print(arr2)

[1 2 3]
[[1]
 [2]
 [3]]


In [27]:
print(arr1+arr2) # 둘다 broadcasting 을 했을경우 모양이 같아지면 계산 가능 
# 둘다 3x3 행렬로 broadcasting 해서 계산 

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [28]:
np.broadcast(arr1,arr2) # 확인 

## 행렬 연산 

> np.dot(arr1, arr2) 

In [29]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
print(arr1*arr2)

[1 4 9]


In [30]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3]).T
print(np.dot(arr1,arr2))

14


In [31]:
print(arr1.dot(arr2))

14


In [32]:
print(arr1@arr2)

14


> 2차원 배열 행렬곱

In [35]:
arr3 = np.arange(1,7).reshape(2,3)
arr4 = np.arange(11,17).reshape(3,2)
print(np.dot(arr3,arr4))

[[ 82  88]
 [199 214]]
